# Generated by Django 4.0.3 on 2024-11-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
    ]
